### General Settings ###
bot.name: "DSpace" # The name of the Discord bot.
bot.version: "V1.0.0" # The version of the Discord bot.

### Formatting ###
format.color.default: "59, 0, 122" # An RGB value for the default embed color.
format.color.error: "255, 0, 48" # An RGB value for the error embed color.

### Assets ###
assets.icon.error: "https://repo.toujoustudios.net/assets/dspace/icon_error.png" # The icon that is shown on error embeds.
assets.icon.search: "https://repo.toujoustudios.net/assets/dspace/icon_search.png" # The icon that is shown on the help command embed.

### Keys ###
keys.token: "" # The bot token.

### Users ###
user.admin: "369381378703228928" # The default admin user.

### Links ###
link.invite: "https://discord.com/api/oauth2/authorize?client_id=872034949685968946&permissions=0&scope=bot%20applications.commands" # The link that should be opened when someone invites the bot.
link.help: "https://toujoustudios.net" # The link to the general bot help website.